server:
  port: 8201
spring:
  profiles: dev
  application:
    name: zzwcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://zzw.eureka7001.com:7001/eureka/
config: 你好 jaja13
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: zzwcloud-config-client
eureka:
  client:
    service-url: 
      defaultZone: http://zzw.eureka7001.com:7001/eureka/