server:
  port: 8201
spring:
  profiles: dev
  application:
    name: zzwcloud-config-client
eureka:
  client:
    service-url: http://zzw.eureka7001.com:7001/eureka/
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: zzwcloud-config-client
eureka:
  client:
    service-url: http://zzw.eureka7001.com:7001/eureka/